### ISSUE TITLE
Is this still actively maintained? (made some updates; added some features...)

### ISSUE THREAD

**Issue by rostwald** [morganwdavis/freebsd-digitalocean#3]
Hi,

After fiddling around with a homegrown script to set up my DO-droplets without all the cruft cloudinit pulls in, I just recently found this project. It worked out of the box and did just exactly what I always needed - so thanks for your efforts!

I made some updates to reflect the state of the current DO droplet images, fixed a minor bug with ssh authorized_keys and also added some small features (droplet resize, execute user-data).

Before dumping everything in just one big pull request, I wanted to check if this project is still actively maintained and if there is any interest in some of my changes:
https://github.com/rostwald/freebsd-digitalocean/commits/master
I've committed everything to the master branch, but let me know if you e.g. want only some diffs merged, then I will create a separate branch for that.

Thanks,
Sebastian

**Comment by morganwdavis** [comment]
Sebastian, so sorry for the delay on this. Somehow I missed the alert on your issue and I just now noticed this. Your contributions look great and I'm happy to merge them all as-is! Thank you for doing this and the fixes.

I haven't had a need to start with any newer DO canned droplets since I've just been using a master snapshot I created years ago and keep upgrading it (now to 12.0-RELEASE). But I'd love to keep this project current with whatever DO is doing now (which looks more like they're making it even messier than it already was).  Bring on the pull request.

**Comment by rostwald** [comment]
No problem, I'll open a PR containing all my commits.

I've also started a cleanroom-reimplementation a few weeks ago that also does the inital configuration/initialization of the droplet (reverting it to a minimal vanilla base-installation) as well as updating from a git repo. It can be kicked off via user-metadata by cloud-init with a few lines, so it won't need any manual interaction on a new droplet and can be used with any configuration management tool (e.g. ansible) that can pass metadata to DO-droplets.
A very early and currently undocumented (at least in the repo) Version is on my gitlab account: https://gitlab.com/rostwald/freebsd-doinit

As I haven't heard from you here I was planning on re-implementing everything myself; but if it is fine with you I'll try to merge all that init- and update-logic into this project (and spare myself from re-inventing the wheel for all the droplet-configuration logic ;))

**Comment by morganwdavis** [comment]
I'm all for whatever helps the FreeBSD community in getting the best experience on DigitalOcean. The most important consideration for me (call it the "prime directive") is that droplets start life as close to a fresh FreeBSD installation as possible with the least resources necessary for self-configuration. I think we should continue to resist additional dependencies for anything, even self-updating via git. A sanctioned update option, like using the FreeBSD pkg system, may be more beneficial to more people (and that was one of the requests for this project).

I do like your sensing when a droplet resize requires the filesystem to expand, but this needs some tweaking. First, it probably should be configurable for sysadmins who might not want that expansion to occur automatically. We'd need to determine a default setting for that config option.  Next, we cannot assume gpt/disk0 because I have original "vanilla" droplets that use zroot/vtbd0p3 with no /dev/gpt/disk0 device. It would either have to discover this or allow the admin to specify which device is the droplet's main storage.

I also like the idea of a script that can clean up a stock DO droplet as a convenience for the sysadmin.  That script should probably be able to deal with all the various droplet versions and the variations DO has made in each release.  The original list that we determined came from their FreeBSD 10 droplet from a couple years ago. 

Given this, and in respect of the prime directive, whatever contributions move it in good direction are fine by me. Should I merge in your PR request as-is, or would you like to refine any of it first?

**Comment by rostwald** [comment]
I fully agree with you on the dependency part - that's why that init script _only_ installs git-lite if the "autoupdate" feature is enabled either by setting that option in the user payload or manually changing it in the config file. Otherwise the script will only do a "pkg delete -yqa && pkg clear" and just removes everything that's not in base. It also removes the additional user DO creates as well as their init scripts and their configuration in rc.conf.
I also agree that updates via pkg would be the best way to go and if this will become a package the first thing I'll rip out is any trace of git patchwork - however, for development/testing this function proved to be very convenient. I think I will keep this functionality in a separate branch but keep it out of the production branch.

Back when I implemented the resizing I only had what DO was shipping at that time for testing (and I was always only using ZFS droplets on DO). If you have some older droplets (ZFS and/or UFS) still running, can you please provide me with information on their disk setup? I'll happily revise that logic and make it more universal/robust as well as making it more configurable. For now I integrated an option to (de)activate it via the config file.

The cleanup logic would be the first thing I'll merge into the existing code. Its not that complex and has no strings attached to any other scripts or logic - so it should be an easy drop-in. If nothing interferes here at work, I'll try to integrate it this afternoon and extend it to work for all currently available droplet variants. I think it is safe to leave out older droplet versions as this logic would be only used to prepare/initialize newly deployed droplets. Do you agree on that?

I just looked over my commits once again and tested everything with a new droplet and it all works as intended. As said I also added an option to (de)activate the resizing feature and a warning that it was only tested with ZFS droplets >11.1. It is deactivated by default, so it won't interfere with older droplet disk configurations.
If it is OK with you I'd suggest to merge the PR as-is and I'll have a look at the resizing-logic once I have additional information about the disk configurations on older droplets.

**Comment by morganwdavis** [comment]
Done! :) Please join me in opening issues for any items we know we need to address next.

In advance of that, some responses to your questions:

ZFS droplets of mine (which started as pure FreeBSD RAM-based installations from official FreeBSD memdisk images) have this layout:

```
# gpart show -l
=>      34  83886013  vtbd0  GPT  (40G)
        34         6         - free -  (3.0K)
        40      1024      1  gptboot0  (512K)
      1064       984         - free -  (492K)
      2048   4194304      2  swap0  (2.0G)
   4196352  79687680      3  zfs0  (38G)
  83884032      2015         - free -  (1.0M)
```
```
# zpool status
  pool: zroot
 state: ONLINE
  scan: scrub repaired 0 in 0 days 00:00:42 with 0 errors on Wed Apr 10 22:49:33 2019
config:

        NAME        STATE     READ WRITE CKSUM
        zroot       ONLINE       0     0     0
          vtbd0p3   ONLINE       0     0     0

errors: No known data errors
```
```
# ls -l /dev/gpt
total 0
crw-r-----  1 root  operator  0x35 Apr  1 22:16 gptboot0
```
And here are the commands I have to issue to expand a resized droplet:
```
# gpart recover vtbd0
# gpart resize -i 3 vtbd0
# zpool set autoexpand=on zroot
# zpool online -e zroot vtbd0p3
```

As for the cleanup script and which DO base images to support, I suppose the latest is fine as that's all I'd ever need it for. I hope there are no requirements from others that would need to install an older base version.

**Comment by rostwald** [comment]
Perfect :)

I already opened new issues for disc resize and the auto prep/init functions, so I think this issue can be marked as closed.
